const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #f0f4ff 0%, #e8f0fe 50%, #f5e8ff 100%)',
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    padding: '24px',
  },
  card: {
    width: '100%',
    maxWidth: '400px',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 20px 60px rgba(0,0,0,0.12)',
    background: '#fff',
  },
  header: {
    background: '#040c22',
    padding: '36px 32px 32px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  brandName: {
    color: 'white',
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0.5px',
    marginTop: '4px',
  },
  tagline: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: '14px',
    margin: '4px 0 0',
    fontWeight: '400',
  },
  body: {
    padding: '32px',
    display: 'flex',
    flexDirection: 'column',
  },
  title: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#111827',
    margin: '0 0 24px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#374151',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: '12px',
    display: 'flex',
    alignItems: 'center',
    pointerEvents: 'none',
  },
  input: {
    width: '100%',
    padding: '11px 12px 11px 38px',
    border: '1.5px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    color: '#111827',
    outline: 'none',
    boxSizing: 'border-box',
    background: '#fff',
  },
  eyeBtn: {
    position: 'absolute',
    right: '12px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    padding: '0',
  },
  submitBtn: {
    marginTop: '4px',
    padding: '13px',
    background: '#040c22',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    letterSpacing: '0.3px',
  },
  erro: {
    color: '#ef4444',
    fontSize: '13px',
    margin: '0',
  },
  demoSection: {
    marginTop: '28px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  demoLabel: {
    fontSize: '12px',
    color: '#9ca3af',
    textAlign: 'center',
    margin: '0 0 4px',
  },
  demoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    border: '1.5px solid #e5e7eb',
    borderRadius: '10px',
    background: '#fafafa',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
  },
  demoRole: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    flex: '1',
  },
  demoEmail: {
    fontSize: '12px',
    color: '#6b7280',
  },
  backLink: {
    marginTop: '20px',
    textAlign: 'center',
    display: 'block',
    fontSize: '13px',
    color: '#7c3aed',
    textDecoration: 'none',
    fontWeight: '500',
  },
};

export default styles;
